# Generated by Django 3.2.6 on 2021-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Digite seu email')),
            ],
        ),
    ]
